dist: trusty
language: php
sudo: required
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
before_install:
  -
      ver=`php --version | grep "PHP 7." | wc -l`
      if [ $ver == 1 ]
      then
      echo "UPDATING PHPUNIT"
      composer install phpunit/phpunit '^7'
      else
      echo "Using PHP Version Below 7"
      composer install phpunit/phpunit '^4'
      fi

install:
before_script:
  - composer update
script:
  - phpunit --bootstrap vendor/autoload.php tests
after_script:
